Alb
MelentQ/auvix pull request #3
Opened 2022-02-21 08:36 UTC by rook16rus

Адаптировал хедер

2022-02-21 18:41 UTC, MelentQ approved these changes

2022-02-21 18:41 UTC, MelentQ commented on src/pages/data/index.json
> +            "name": "img/promotion-1.png",
Это image уж, а не name)
Во всём json так

2022-02-21 18:41 UTC, MelentQ commented on src/scss/components/products.scss
> +    width: calc((100% - 12px) / 4);
Здесь странное что-то. Не могу проверить зачем именно так, нужно залить на gh pages

2022-02-21 18:41 UTC, MelentQ commented on src/scss/components/products.scss
> +    width: calc((100% - 12px) / 4);
Возможно здесь лучше гриды?

2022-02-21 18:41 UTC, MelentQ commented on src/scss/global/_mixins.scss
> +@mixin productSvgLocation() {
Нвыерное этот миксин можно было оставить внутри файла products.scss. Потому что вряд ли еще где-то будет использоваться. А сюда нужно помещать именно универсальные миксины

2022-02-22 06:52 UTC, rook16rus commented on src/scss/components/products.scss
> +    width: calc((100% - 12px) / 4);
Свойство width здесь нужно совсем убрать, т.к. слайдер сам рассчитывает ширину и перезаписывает свойство инлайново.

А flex-direction и jusctify-content здесь для того, чтобы распределить заголовок и ссылку карточки в разные стороны вертикально.

2022-02-22 21:01 UTC, MelentQ requested changes
Норм) + накидал по визуалу в ЛС

2022-02-22 21:01 UTC, MelentQ commented on src/scss/components/academy.scss
> +    background: #B659FF url(../img/request-bg.svg) no-repeat right 0;
Лучше конечно через img, вдруг захотят поменять? Через CSS сложно будет

2022-02-24 13:26 UTC, merged